version: "3.8"
services:
  api:
    image: sarmad-cars
    build: .
    container_name: sarmad-cars
    ports:
      - "8080:8080"
    networks:
        - api-network

networks:
  api-network:
    driver: bridge